version: '4'
services:
  gpodder:
    image: php8
    container_name: micro-gpodder-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${DATA_DIR}
        target: /var/www/html/data
    ports:
      - "443:443"